# .spectral.yaml
  path-param-style:
    description: "Path parameters should be declared using braces and use simple names (e.g., {orderId})."
    given: "$.paths[*]"
    severity: warn
    then:
      function: pattern
      functionOptions:
        match: "^/.*(\\{[a-zA-Z0-9]+\\}).*$"

  # Responses & error handling
  responses-have-description:
    description: "All responses must include a description."
    given: "$.paths[*][*].responses[*]"
    severity: error
    then:
      field: description
      function: truthy

  responses-include-content:
    description: "Responses should include a content object (e.g., application/json)."
    given: "$.paths[*][*].responses[*]"
    severity: warn
    then:
      field: content
      function: truthy

  # Enforce Problem+JSON presence
  components-problem-schema:
    description: "Repository should define a Problem (Problem+JSON) schema in components.schemas named 'Problem'."
    given: "$.components.schemas"
    severity: warn
    then:
      field: Problem
      function: truthy

  # Security & examples
  no-bearer-in-examples:
    description: "Do not include bearer tokens / secrets in examples."
    given: "$..example"
    severity: error
    then:
      function: pattern
      functionOptions:
        match: "(?i)(Authorization\\s*:\\s*Bearer\\s+|Bearer\\s+[A-Za-z0-9\\-\\._~\\+\\/]+=*|\\bapi[_-]?key\\b|\\bsecret\\b)"

  examples-present:
    description: "Operations should provide at least one example for request or response where applicable."
    given: "$.paths[*][*]"
    severity: warn
    then:
      function: or
      functionOptions:
        functions:
          - name: truthy
            field: requestBody.content
          - name: truthy
            field: responses.*.content

  # Pagination hint (best-effort)
  pagination-params:
    description: "If collection endpoints exist, recommend standard pagination params: limit, after/page, offset, sort."
    given: "$.paths[*]"
    severity: info
    then:
      function: pattern
      functionOptions:
        match: "(limit|after|page|offset|sort)"

  # Non-empty summaries
  no-empty-summaries:
    description: "Operation summaries should not be empty."
    given: "$.paths[*][*].summary"
    severity: warn
    then:
      function: pattern
      functionOptions:
        match: "\\S+"